In [129]:
import os
import pandas as pd
import numpy as np
from alpha_vantage.timeseries import TimeSeries
import csv
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn import preprocessing
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score

# Loading historic stock data

In [130]:
key = 'E4M6BVAOLPUG2OL7'
ts = TimeSeries(key, output_format='pandas')

In [134]:
data, googl_meta_data = ts.get_daily('GOOGL', outputsize='full')
data = data.rename_axis(['Date'])
data

1. open  2. high     3. low  4. close   5. volume
Date                                                         
2019-11-27  1315.42  1317.64  1309.4742  1312.060    638435.0
2019-11-26  1309.91  1314.01  1304.0400  1313.000    940545.0
2019-11-25  1296.26  1310.41  1295.6100  1305.640   1179658.0
2019-11-22  1303.00  1306.90  1289.3600  1293.670   1388912.0
2019-11-21  1299.25  1311.12  1290.7500  1300.140   1277338.0
...             ...      ...        ...       ...         ...
2004-08-25   104.76   108.00   103.8800   106.000   9188600.0
2004-08-24   111.24   111.60   103.5700   104.870  15247300.0
2004-08-23   110.76   113.48   109.0500   109.400  18256100.0
2004-08-20   101.01   109.08   100.5000   108.310  22834300.0
2004-08-19   100.01   104.06    95.9600   100.335  44659000.0

[3847 rows x 5 columns]

In [135]:
data = data.rename(columns={'1. open': 'Open', '2. high':'High', '3. low':'Low', '4. close':'Close', '5. volume':'Volume'})

In [136]:
path = str(os.getcwd()) + "/" + "data"
data.to_csv("trainData.csv")

# Feature Engineering

In [137]:
def read_train():
    prices = pd.read_csv("trainData.csv")
    prices = clean(prices)
    return prices

def clean(prices):
    (m, n) = prices.shape

    prices = prices.loc[:, ['Date', 'Open', 'Close']]

    # Add new column "Close Price at the Previous Day" and "Open Price at the Previous Day"
    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-1)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev')

    # Add new column "Close Price at the Day Before" and "Open Price at the Day Before"
    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-2)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev2')

    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-3)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev3')

    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-4)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev4')

    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-5)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev5')



    # No need now to save the fifth days data
    prices = prices[:m-5]

    return prices


def write_train(data):
    data.loc[:, ['Date','Open','OpenPrev','ClosePrev','OpenPrev2','ClosePrev2','OpenPrev3','ClosePrev3',
                 'OpenPrev4','ClosePrev4','OpenPrev5','ClosePrev5']].to_csv("trainX.csv", index=False)
    data.loc[:, ['Close']].to_csv( "trainY.csv",index=False)
    
def write_test(data):
    print(year_Y_2017)
    year_2017=data.loc[mask]
    year_2017.loc[:, ['Date','Open','OpenPrev','ClosePrev','OpenPrev2','ClosePrev2','OpenPrev3','ClosePrev3',
                 'OpenPrev4','ClosePrev4','OpenPrev5','ClosePrev5']].to_csv("trainX.csv", index=False)
    year_2017.loc[:, ['Close']].to_csv( "trainY.csv",index=False)

# Evaluate Linear Regression and predict stock price

In [186]:
def read_val():
    X = pd.read_csv("trainX.csv", header=0)
    y = pd.read_csv("trainY.csv", header=0)
    X['Date'] = pd.to_datetime(X['Date'], format='%Y-%m-%d')
    return X, y



def plot_trend(x, predict, y, title):
    plt.xticks(rotation=45)
    plt.plot_date(x, y, fmt='b-', xdate=True, ydate=False, label='Real value')
    plt.plot_date(x, predict, fmt='r-', xdate=True, ydate=False, label='Predicted value')
    plt.legend(loc='upper center')
    plt.ylabel('Close prices')
    plt.title(title)
    plt.grid()
    plt.show()


def modify(X, columns):
    columns.append('Date2num')
    returnX = X.loc[:, columns]
    return returnX


def predict_and_plot(X, date):
    m, n = X.shape
    X_test = X.loc[np.floor(m*0.6)+1:]
    X_train = X.loc[:np.floor(m*0.6)]
    
    y_test = y.loc[np.floor(m*0.6)+1:]
    y_train = y.loc[:np.floor(m*0.6)]
    
    date_test = date.loc[np.floor(m*0.6)+1:]
    date_train = date.loc[:np.floor(m*0.6)]
    
    lr = LinearRegression()

    lr.fit(X_train, y_train)

    print('Coefficients: \n', lr.coef_)
    print('Intercept: \n', lr.intercept_)
    pred = lr.predict(X_test)
    
    return lr,pred

In [198]:
prices_train=read_train()
write_train(prices_train)

X, y = read_val()

X['Date2num'] = X['Date'].apply(lambda x: mdates.date2num(x))
date = X.loc[:, ['Date']]
del X['Date']

X1 = modify(X, [])
predict_and_plot(X1,date)

Coefficients: 
 [[0.17890297]]
Intercept: 
 [-130806.5204398]


(LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 array([[516.30979642],
        [516.13089345],
        [515.95199048],
        ...,
        [118.78739822],
        [118.25068931],
        [118.07178634]]))

# Predict stock price after dimensionality reduction

In [199]:
X3 = modify(X, ['Open','OpenPrev','ClosePrev'])
lr,close_val=predict_and_plot(X3, date)
X3

Coefficients: 
 [[ 1.00056646e+00  3.60356692e-02 -3.83317501e-02  5.08682983e-04]]
Intercept: 
 [-372.91109733]


Open  OpenPrev  ClosePrev  Date2num
0     1315.42   1309.91    1313.00  737390.0
1     1309.91   1296.26    1305.64  737389.0
2     1296.26   1303.00    1293.67  737388.0
3     1303.00   1299.25    1300.14  737385.0
4     1299.25   1311.36    1301.86  737384.0
...       ...       ...        ...       ...
3837   102.70    102.32     102.37  731825.0
3838   102.32    105.28     102.01  731824.0
3839   105.28    108.10     106.15  731823.0
3840   108.10    104.95     107.91  731820.0
3841   104.95    104.76     106.00  731819.0

[3842 rows x 4 columns]

# Load the Business days only

In [189]:
from collections import OrderedDict
from datetime import datetime

daterange = pd.date_range('1995-01-01', datetime.today().strftime('%Y-%m-%d'), freq='B')
newDate = pd.DataFrame(data=daterange, columns=['date'])
newDate = newDate.dropna()
newDate

date
0    1995-01-02
1    1995-01-03
2    1995-01-04
3    1995-01-05
4    1995-01-06
...         ...
6493 2019-11-21
6494 2019-11-22
6495 2019-11-25
6496 2019-11-26
6497 2019-11-27

[6498 rows x 1 columns]

# Load the stock prices for the above dates and predict

In [190]:
prevOpen = data.loc[:,['Open']]
prevOpen = prevOpen.iloc[len(prevOpen)-1]
prevClose = close_val.item(len(close_val)-1)
prevOpen = prevOpen.values.item(0)
newX3 = X3
try:
    newX3.drop('Date2num',axis=1,inplace=True)
except:
    print('already dropped')
dummy = pd.DataFrame([[prevClose,prevOpen,prevClose]], columns=['Open','OpenPrev','ClosePrev'])
newX3 = newX3.append(dummy, ignore_index=True)
date = date.append(newDate, ignore_index=True)
for x in range(0,len(newDate)-1):
    print(len(newX3))
    print(len(date))
    lr,close_val = predict_and_plot(newX3, date)
    prevClose = close_val.item(len(close_val)-1)
    prevOpen = newX3.loc[:,['Open']]
    prevOpen = prevOpen.iloc[len(prevOpen)-1]
    prevOpen = prevOpen.values.item(0)
    dummy = pd.DataFrame([[prevClose,prevOpen,prevClose]], columns=['Open','OpenPrev','ClosePrev'])
    newX3 = newX3.append(dummy, ignore_index=True)

newX3

/usr/local/lib/python3.7/site-packages/pandas/core/frame.py:7138: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,


3843
10340
Coefficients: 
 [[ 1.0012921   0.03647955 -0.03792819]]
Intercept: 
 [0.05362603]
3844
10340
Coefficients: 
 [[ 1.00128836  0.03648502 -0.03792219]]
Intercept: 
 [0.04587441]
3845
10340
Coefficients: 
 [[ 1.00128847  0.03647566 -0.03791212]]
Intercept: 
 [0.0450569]
3846
10340
Coefficients: 
 [[ 1.00128847  0.03647566 -0.03791212]]
Intercept: 
 [0.0450569]
3847
10340
Coefficients: 
 [[ 1.00126027  0.03653377 -0.0379278 ]]
Intercept: 
 [0.03076804]
3848
10340
Coefficients: 
 [[ 1.00126027  0.03653377 -0.0379278 ]]
Intercept: 
 [0.03076804]
3849
10340
Coefficients: 
 [[ 1.0012621   0.03648432 -0.03788441]]
Intercept: 
 [0.03499483]
3850
10340
Coefficients: 
 [[ 1.0013501   0.03650091 -0.03800215]]
Intercept: 
 [0.04806583]
3851
10340
Coefficients: 
 [[ 1.0013501   0.03650091 -0.03800215]]
Intercept: 
 [0.04806583]
3852
10340
Coefficients: 
 [[ 1.00135537  0.03651739 -0.03802151]]
Intercept: 
 [0.04569445]
3853
10340
Coefficients: 
 [[ 1.00135537  0.03651739 -0.03802151]]
Inter

3941
10340
Coefficients: 
 [[ 1.00166132  0.03602758 -0.03797435]]
Intercept: 
 [0.17874281]
3942
10340
Coefficients: 
 [[ 1.00167618  0.03584013 -0.0378112 ]]
Intercept: 
 [0.18778977]
3943
10340
Coefficients: 
 [[ 1.00167618  0.03584013 -0.0378112 ]]
Intercept: 
 [0.18778977]
3944
10340
Coefficients: 
 [[ 1.00170961  0.03622172 -0.03825827]]
Intercept: 
 [0.21849291]
3945
10340
Coefficients: 
 [[ 1.00159424  0.03605364 -0.03795213]]
Intercept: 
 [0.19678804]
3946
10340
Coefficients: 
 [[ 1.00159424  0.03605364 -0.03795213]]
Intercept: 
 [0.19678804]
3947
10340
Coefficients: 
 [[ 1.00158066  0.03592814 -0.03779832]]
Intercept: 
 [0.1826646]
3948
10340
Coefficients: 
 [[ 1.00158066  0.03592814 -0.03779832]]
Intercept: 
 [0.1826646]
3949
10340
Coefficients: 
 [[ 1.00158764  0.03566607 -0.03752652]]
Intercept: 
 [0.16657831]
3950
10340
Coefficients: 
 [[ 1.0015912   0.03526664 -0.03710348]]
Intercept: 
 [0.14031115]
3951
10340
Coefficients: 
 [[ 1.0015912   0.03526664 -0.03710348]]
Inter

Coefficients: 
 [[ 1.00295427  0.0366928  -0.03962688]]
Intercept: 
 [-0.12471441]
4044
10340
Coefficients: 
 [[ 1.00295836  0.03672392 -0.0396713 ]]
Intercept: 
 [-0.11512402]
4045
10340
Coefficients: 
 [[ 1.00295967  0.03675506 -0.03970111]]
Intercept: 
 [-0.11785709]
4046
10340
Coefficients: 
 [[ 1.00295967  0.03675506 -0.03970111]]
Intercept: 
 [-0.11785709]
4047
10340
Coefficients: 
 [[ 1.00295105  0.03681465 -0.03975914]]
Intercept: 
 [-0.11050957]
4048
10340
Coefficients: 
 [[ 1.00295105  0.03681465 -0.03975914]]
Intercept: 
 [-0.11050957]
4049
10340
Coefficients: 
 [[ 1.0029647   0.03680254 -0.03975444]]
Intercept: 
 [-0.11702704]
4050
10340
Coefficients: 
 [[ 1.00297042  0.03680554 -0.03976128]]
Intercept: 
 [-0.11899718]
4051
10340
Coefficients: 
 [[ 1.00297042  0.03680554 -0.03976128]]
Intercept: 
 [-0.11899718]
4052
10340
Coefficients: 
 [[ 1.00297077  0.03680665 -0.03976294]]
Intercept: 
 [-0.11878777]
4053
10340
Coefficients: 
 [[ 1.00297077  0.03680665 -0.03976294]]
Inte

Coefficients: 
 [[ 1.00297061  0.03673538 -0.03967385]]
Intercept: 
 [-0.1396359]
4151
10340
Coefficients: 
 [[ 1.00297061  0.03673538 -0.03967385]]
Intercept: 
 [-0.1396359]
4152
10340
Coefficients: 
 [[ 1.00292241  0.03652003 -0.0393895 ]]
Intercept: 
 [-0.16314924]
4153
10340
Coefficients: 
 [[ 1.00292241  0.03652003 -0.0393895 ]]
Intercept: 
 [-0.16314924]
4154
10340
Coefficients: 
 [[ 1.00292397  0.03652261 -0.03938999]]
Intercept: 
 [-0.16727158]
4155
10340
Coefficients: 
 [[ 1.00292035  0.03651754 -0.03938099]]
Intercept: 
 [-0.16762003]
4156
10340
Coefficients: 
 [[ 1.00292035  0.03651754 -0.03938099]]
Intercept: 
 [-0.16762003]
4157
10340
Coefficients: 
 [[ 1.00290831  0.0366077  -0.03945355]]
Intercept: 
 [-0.1738444]
4158
10340
Coefficients: 
 [[ 1.00290831  0.0366077  -0.03945355]]
Intercept: 
 [-0.1738444]
4159
10340
Coefficients: 
 [[ 1.00289514  0.03669703 -0.03953474]]
Intercept: 
 [-0.16819094]
4160
10340
Coefficients: 
 [[ 1.00288219  0.03673294 -0.03955139]]
Intercep

4249
10340
Coefficients: 
 [[ 1.00282331  0.03638561 -0.0392144 ]]
Intercept: 
 [-0.1030823]
4250
10340
Coefficients: 
 [[ 1.00283268  0.03638544 -0.0392249 ]]
Intercept: 
 [-0.10179303]
4251
10340
Coefficients: 
 [[ 1.00283268  0.03638544 -0.0392249 ]]
Intercept: 
 [-0.10179303]
4252
10340
Coefficients: 
 [[ 1.00283085  0.03637492 -0.03921162]]
Intercept: 
 [-0.10272076]
4253
10340
Coefficients: 
 [[ 1.00283085  0.03637492 -0.03921162]]
Intercept: 
 [-0.10272076]
4254
10340
Coefficients: 
 [[ 1.00282361  0.03675539 -0.03957556]]
Intercept: 
 [-0.11187462]
4255
10340
Coefficients: 
 [[ 1.00279058  0.03613496 -0.03896122]]
Intercept: 
 [-0.07358534]
4256
10340
Coefficients: 
 [[ 1.00279058  0.03613496 -0.03896122]]
Intercept: 
 [-0.07358534]
4257
10340
Coefficients: 
 [[ 1.0028249   0.03609186 -0.03896736]]
Intercept: 
 [-0.05904196]
4258
10340
Coefficients: 
 [[ 1.0028249   0.03609186 -0.03896736]]
Intercept: 
 [-0.05904196]
4259
10340
Coefficients: 
 [[ 1.00282933  0.03608608 -0.03896

4357
10340
Coefficients: 
 [[ 1.00291167  0.03499127 -0.03806882]]
Intercept: 
 [0.04929081]
4358
10340
Coefficients: 
 [[ 1.00291167  0.03499127 -0.03806882]]
Intercept: 
 [0.04929081]
4359
10340
Coefficients: 
 [[ 1.00289081  0.03488688 -0.03795606]]
Intercept: 
 [0.06095878]
4360
10340
Coefficients: 
 [[ 1.00291446  0.03483004 -0.03793387]]
Intercept: 
 [0.07119226]
4361
10340
Coefficients: 
 [[ 1.00291446  0.03483004 -0.03793387]]
Intercept: 
 [0.07119226]
4362
10340
Coefficients: 
 [[ 1.00292596  0.03492885 -0.03804933]]
Intercept: 
 [0.0759915]
4363
10340
Coefficients: 
 [[ 1.00292596  0.03492885 -0.03804933]]
Intercept: 
 [0.0759915]
4364
10340
Coefficients: 
 [[ 1.00298713  0.03511218 -0.03826519]]
Intercept: 
 [0.04924396]
4365
10340
Coefficients: 
 [[ 1.00296931  0.0351906  -0.03833285]]
Intercept: 
 [0.05584434]
4366
10340
Coefficients: 
 [[ 1.00296931  0.0351906  -0.03833285]]
Intercept: 
 [0.05584434]
4367
10340
Coefficients: 
 [[ 1.00303733  0.03505103 -0.03824444]]
Inter

4456
10340
Coefficients: 
 [[ 1.0029808   0.03404873 -0.03723662]]
Intercept: 
 [0.08668944]
4457
10340
Coefficients: 
 [[ 1.00299226  0.03362639 -0.03684522]]
Intercept: 
 [0.1046047]
4458
10340
Coefficients: 
 [[ 1.00299226  0.03362639 -0.03684522]]
Intercept: 
 [0.1046047]
4459
10340
Coefficients: 
 [[ 1.00292297  0.03401169 -0.03719172]]
Intercept: 
 [0.13266048]
4460
10340
Coefficients: 
 [[ 1.00296233  0.0342572  -0.03745677]]
Intercept: 
 [0.11441579]
4461
10340
Coefficients: 
 [[ 1.00296233  0.0342572  -0.03745677]]
Intercept: 
 [0.11441579]
4462
10340
Coefficients: 
 [[ 1.00292903  0.03415287 -0.03733658]]
Intercept: 
 [0.13045126]
4463
10340
Coefficients: 
 [[ 1.00292903  0.03415287 -0.03733658]]
Intercept: 
 [0.13045126]
4464
10340
Coefficients: 
 [[ 1.00296924  0.0341655  -0.0373968 ]]
Intercept: 
 [0.13719985]
4465
10340
Coefficients: 
 [[ 1.00295515  0.03414067 -0.03735353]]
Intercept: 
 [0.13322612]
4466
10340
Coefficients: 
 [[ 1.00295515  0.03414067 -0.03735353]]
Inter

Coefficients: 
 [[ 1.00349333  0.03552125 -0.03940289]]
Intercept: 
 [0.2504178]
4564
10340
Coefficients: 
 [[ 1.00348414  0.0355512  -0.03942971]]
Intercept: 
 [0.25586796]
4565
10340
Coefficients: 
 [[ 1.00347982  0.03534118 -0.03920457]]
Intercept: 
 [0.2461227]
4566
10340
Coefficients: 
 [[ 1.00347982  0.03534118 -0.03920457]]
Intercept: 
 [0.2461227]
4567
10340
Coefficients: 
 [[ 1.00344943  0.0357224  -0.03952349]]
Intercept: 
 [0.21733704]
4568
10340
Coefficients: 
 [[ 1.00344943  0.0357224  -0.03952349]]
Intercept: 
 [0.21733704]
4569
10340
Coefficients: 
 [[ 1.00338444  0.0358817  -0.03963472]]
Intercept: 
 [0.23263784]
4570
10340
Coefficients: 
 [[ 1.0034763   0.03592532 -0.03975411]]
Intercept: 
 [0.21803524]
4571
10340
Coefficients: 
 [[ 1.0034763   0.03592532 -0.03975411]]
Intercept: 
 [0.21803524]
4572
10340
Coefficients: 
 [[ 1.00348613  0.03588724 -0.03972896]]
Intercept: 
 [0.22083489]
4573
10340
Coefficients: 
 [[ 1.00348613  0.03588724 -0.03972896]]
Intercept: 
 [0.2

Coefficients: 
 [[ 1.00346818  0.03903043 -0.04281578]]
Intercept: 
 [0.18151393]
4668
10340
Coefficients: 
 [[ 1.00346818  0.03903043 -0.04281578]]
Intercept: 
 [0.18151393]
4669
10340
Coefficients: 
 [[ 1.00469874  0.03704594 -0.04212171]]
Intercept: 
 [0.23531126]
4670
10340
Coefficients: 
 [[ 1.00406691  0.03814391 -0.0426298 ]]
Intercept: 
 [0.27354605]
4671
10340
Coefficients: 
 [[ 1.00406691  0.03814391 -0.0426298 ]]
Intercept: 
 [0.27354605]
4672
10340
Coefficients: 
 [[ 1.00389264  0.03866123 -0.04293768]]
Intercept: 
 [0.24167713]
4673
10340
Coefficients: 
 [[ 1.00389264  0.03866123 -0.04293768]]
Intercept: 
 [0.24167713]
4674
10340
Coefficients: 
 [[ 1.00366045  0.03939715 -0.04345615]]
Intercept: 
 [0.2552383]
4675
10340
Coefficients: 
 [[ 1.00358051  0.03913496 -0.04305709]]
Intercept: 
 [0.20270251]
4676
10340
Coefficients: 
 [[ 1.00358051  0.03913496 -0.04305709]]
Intercept: 
 [0.20270251]
4677
10340
Coefficients: 
 [[ 1.00367419  0.03897024 -0.04297954]]
Intercept: 
 [0

Coefficients: 
 [[ 1.00353141  0.03856411 -0.04217897]]
Intercept: 
 [-0.04995016]
4779
10340
Coefficients: 
 [[ 1.00350124  0.0384017  -0.04198153]]
Intercept: 
 [-0.05518061]
4780
10340
Coefficients: 
 [[ 1.00358517  0.03872786 -0.04238225]]
Intercept: 
 [-0.06527668]
4781
10340
Coefficients: 
 [[ 1.00358517  0.03872786 -0.04238225]]
Intercept: 
 [-0.06527668]
4782
10340
Coefficients: 
 [[ 1.0036008   0.03865772 -0.04233782]]
Intercept: 
 [-0.05451062]
4783
10340
Coefficients: 
 [[ 1.0036008   0.03865772 -0.04233782]]
Intercept: 
 [-0.05451062]
4784
10340
Coefficients: 
 [[ 1.00361905  0.03861136 -0.04231183]]
Intercept: 
 [-0.0522685]
4785
10340
Coefficients: 
 [[ 1.00366168  0.0387987  -0.04254818]]
Intercept: 
 [-0.04555772]
4786
10340
Coefficients: 
 [[ 1.00366168  0.0387987  -0.04254818]]
Intercept: 
 [-0.04555772]
4787
10340
Coefficients: 
 [[ 1.00365997  0.03927167 -0.04300984]]
Intercept: 
 [-0.05556427]
4788
10340
Coefficients: 
 [[ 1.00365997  0.03927167 -0.04300984]]
Inter

Coefficients: 
 [[ 1.00415121  0.03999488 -0.044197  ]]
Intercept: 
 [-0.08980241]
4887
10340
Coefficients: 
 [[ 1.00419881  0.04000073 -0.04424331]]
Intercept: 
 [-0.09685848]
4888
10340
Coefficients: 
 [[ 1.00419881  0.04000073 -0.04424331]]
Intercept: 
 [-0.09685848]
4889
10340
Coefficients: 
 [[ 1.00420335  0.0399761  -0.04422388]]
Intercept: 
 [-0.09621897]
4890
10340
Coefficients: 
 [[ 1.00423945  0.04030193 -0.04460621]]
Intercept: 
 [-0.07642148]
4891
10340
Coefficients: 
 [[ 1.00423945  0.04030193 -0.04460621]]
Intercept: 
 [-0.07642148]
4892
10340
Coefficients: 
 [[ 1.00430322  0.04020864 -0.04456714]]
Intercept: 
 [-0.08577548]
4893
10340
Coefficients: 
 [[ 1.00430322  0.04020864 -0.04456714]]
Intercept: 
 [-0.08577548]
4894
10340
Coefficients: 
 [[ 1.00428161  0.04044572 -0.04477746]]
Intercept: 
 [-0.09075774]
4895
10340
Coefficients: 
 [[ 1.00452257  0.04008092 -0.04468246]]
Intercept: 
 [-0.06325243]
4896
10340
Coefficients: 
 [[ 1.00452257  0.04008092 -0.04468246]]
Inte

4996
10340
Coefficients: 
 [[ 1.00334789  0.04600258 -0.04936384]]
Intercept: 
 [-0.14965601]
4997
10340
Coefficients: 
 [[ 1.00333027  0.04580378 -0.04914592]]
Intercept: 
 [-0.15334519]
4998
10340
Coefficients: 
 [[ 1.00333027  0.04580378 -0.04914592]]
Intercept: 
 [-0.15334519]
4999
10340
Coefficients: 
 [[ 1.00339215  0.04574802 -0.04915084]]
Intercept: 
 [-0.15657755]
5000
10340
Coefficients: 
 [[ 1.00337196  0.04569049 -0.04907276]]
Intercept: 
 [-0.1576719]
5001
10340
Coefficients: 
 [[ 1.00337196  0.04569049 -0.04907276]]
Intercept: 
 [-0.1576719]
5002
10340
Coefficients: 
 [[ 1.00342183  0.04593949 -0.04937052]]
Intercept: 
 [-0.16041141]
5003
10340
Coefficients: 
 [[ 1.00342183  0.04593949 -0.04937052]]
Intercept: 
 [-0.16041141]
5004
10340
Coefficients: 
 [[ 1.00336583  0.04567048 -0.04904815]]
Intercept: 
 [-0.15431986]
5005
10340
Coefficients: 
 [[ 1.00334096  0.04569126 -0.04904523]]
Intercept: 
 [-0.15150083]
5006
10340
Coefficients: 
 [[ 1.00334096  0.04569126 -0.049045

Coefficients: 
 [[ 1.00311342  0.04042136 -0.04357875]]
Intercept: 
 [-0.14058262]
5105
10340
Coefficients: 
 [[ 1.00311287  0.04042499 -0.04358204]]
Intercept: 
 [-0.14033164]
5106
10340
Coefficients: 
 [[ 1.00311287  0.04042499 -0.04358204]]
Intercept: 
 [-0.14033164]
5107
10340
Coefficients: 
 [[ 1.0030874   0.0403971  -0.04352519]]
Intercept: 
 [-0.14424065]
5108
10340
Coefficients: 
 [[ 1.0030874   0.0403971  -0.04352519]]
Intercept: 
 [-0.14424065]
5109
10340
Coefficients: 
 [[ 1.00308474  0.04043298 -0.04355678]]
Intercept: 
 [-0.14606033]
5110
10340
Coefficients: 
 [[ 1.00303197  0.04028798 -0.04336393]]
Intercept: 
 [-0.14061904]
5111
10340
Coefficients: 
 [[ 1.00303197  0.04028798 -0.04336393]]
Intercept: 
 [-0.14061904]
5112
10340
Coefficients: 
 [[ 1.00303517  0.04017967 -0.04326553]]
Intercept: 
 [-0.13329105]
5113
10340
Coefficients: 
 [[ 1.00303517  0.04017967 -0.04326553]]
Intercept: 
 [-0.13329105]
5114
10340
Coefficients: 
 [[ 1.0030585   0.04008829 -0.04320143]]
Inte

Coefficients: 
 [[ 1.00237915  0.04006301 -0.04254642]]
Intercept: 
 [-0.07749664]
5215
10340
Coefficients: 
 [[ 1.00235613  0.0400527  -0.04251066]]
Intercept: 
 [-0.08003732]
5216
10340
Coefficients: 
 [[ 1.00235613  0.0400527  -0.04251066]]
Intercept: 
 [-0.08003732]
5217
10340
Coefficients: 
 [[ 1.00234908  0.0400872  -0.04253694]]
Intercept: 
 [-0.08124409]
5218
10340
Coefficients: 
 [[ 1.00234908  0.0400872  -0.04253694]]
Intercept: 
 [-0.08124409]
5219
10340
Coefficients: 
 [[ 1.00237764  0.03997723 -0.04246527]]
Intercept: 
 [-0.07131449]
5220
10340
Coefficients: 
 [[ 1.00238073  0.0400463  -0.04254066]]
Intercept: 
 [-0.06802541]
5221
10340
Coefficients: 
 [[ 1.00238073  0.0400463  -0.04254066]]
Intercept: 
 [-0.06802541]
5222
10340
Coefficients: 
 [[ 1.00235297  0.04006323 -0.04252235]]
Intercept: 
 [-0.07565782]
5223
10340
Coefficients: 
 [[ 1.00235297  0.04006323 -0.04252235]]
Intercept: 
 [-0.07565782]
5224
10340
Coefficients: 
 [[ 1.00234973  0.04003667 -0.04249345]]
Inte

Coefficients: 
 [[ 1.00206948  0.03988137 -0.04207564]]
Intercept: 
 [-0.05735468]
5320
10340
Coefficients: 
 [[ 1.00206783  0.03987501 -0.04206811]]
Intercept: 
 [-0.05688838]
5321
10340
Coefficients: 
 [[ 1.00206783  0.03987501 -0.04206811]]
Intercept: 
 [-0.05688838]
5322
10340
Coefficients: 
 [[ 1.00204944  0.03986099 -0.04204173]]
Intercept: 
 [-0.0510703]
5323
10340
Coefficients: 
 [[ 1.00204944  0.03986099 -0.04204173]]
Intercept: 
 [-0.0510703]
5324
10340
Coefficients: 
 [[ 1.0020473   0.03984278 -0.04202238]]
Intercept: 
 [-0.05010483]
5325
10340
Coefficients: 
 [[ 1.00202084  0.0395544  -0.04171724]]
Intercept: 
 [-0.04083877]
5326
10340
Coefficients: 
 [[ 1.00202084  0.0395544  -0.04171724]]
Intercept: 
 [-0.04083877]
5327
10340
Coefficients: 
 [[ 1.00200519  0.0395555  -0.04171844]]
Intercept: 
 [-0.02587534]
5328
10340
Coefficients: 
 [[ 1.00200519  0.0395555  -0.04171844]]
Intercept: 
 [-0.02587534]
5329
10340
Coefficients: 
 [[ 1.00200633  0.03955949 -0.04172322]]
Interc

Coefficients: 
 [[ 1.00218232  0.04068465 -0.04295364]]
Intercept: 
 [-0.09700955]
5414
10340
Coefficients: 
 [[ 1.00220243  0.04058151 -0.04288861]]
Intercept: 
 [-0.07958708]
5415
10340
Coefficients: 
 [[ 1.00221849  0.04058839 -0.04291361]]
Intercept: 
 [-0.07760716]
5416
10340
Coefficients: 
 [[ 1.00221849  0.04058839 -0.04291361]]
Intercept: 
 [-0.07760716]
5417
10340
Coefficients: 
 [[ 1.00222208  0.04056459 -0.0428913 ]]
Intercept: 
 [-0.07962423]
5418
10340
Coefficients: 
 [[ 1.00222208  0.04056459 -0.0428913 ]]
Intercept: 
 [-0.07962423]
5419
10340
Coefficients: 
 [[ 1.00223669  0.04068633 -0.04302243]]
Intercept: 
 [-0.08467404]
5420
10340
Coefficients: 
 [[ 1.0022656   0.04064454 -0.04302008]]
Intercept: 
 [-0.07457208]
5421
10340
Coefficients: 
 [[ 1.0022656   0.04064454 -0.04302008]]
Intercept: 
 [-0.07457208]
5422
10340
Coefficients: 
 [[ 1.00226619  0.04064985 -0.04302734]]
Intercept: 
 [-0.07327345]
5423
10340
Coefficients: 
 [[ 1.00226619  0.04064985 -0.04302734]]
Inte

5514
10340
Coefficients: 
 [[ 1.00225019  0.04239844 -0.04474093]]
Intercept: 
 [-0.0934417]
5515
10340
Coefficients: 
 [[ 1.00225948  0.04248807 -0.04483641]]
Intercept: 
 [-0.09661481]
5516
10340
Coefficients: 
 [[ 1.00225948  0.04248807 -0.04483641]]
Intercept: 
 [-0.09661481]
5517
10340
Coefficients: 
 [[ 1.00226139  0.0423636  -0.04473042]]
Intercept: 
 [-0.08142089]
5518
10340
Coefficients: 
 [[ 1.00226139  0.0423636  -0.04473042]]
Intercept: 
 [-0.08142089]
5519
10340
Coefficients: 
 [[ 1.00225608  0.04236272 -0.04472854]]
Intercept: 
 [-0.07747284]
5520
10340
Coefficients: 
 [[ 1.00225676  0.04235832 -0.04472412]]
Intercept: 
 [-0.07812363]
5521
10340
Coefficients: 
 [[ 1.00225676  0.04235832 -0.04472412]]
Intercept: 
 [-0.07812363]
5522
10340
Coefficients: 
 [[ 1.0022519   0.04235861 -0.04471487]]
Intercept: 
 [-0.08240585]
5523
10340
Coefficients: 
 [[ 1.0022519   0.04235861 -0.04471487]]
Intercept: 
 [-0.08240585]
5524
10340
Coefficients: 
 [[ 1.00225142  0.04235349 -0.04470

5607
10340
Coefficients: 
 [[ 1.00200514  0.04281173 -0.04490805]]
Intercept: 
 [-0.09489481]
5608
10340
Coefficients: 
 [[ 1.00200514  0.04281173 -0.04490805]]
Intercept: 
 [-0.09489481]
5609
10340
Coefficients: 
 [[ 1.00199187  0.04289516 -0.04496904]]
Intercept: 
 [-0.10332739]
5610
10340
Coefficients: 
 [[ 1.00199507  0.04296239 -0.04504383]]
Intercept: 
 [-0.09931989]
5611
10340
Coefficients: 
 [[ 1.00199507  0.04296239 -0.04504383]]
Intercept: 
 [-0.09931989]
5612
10340
Coefficients: 
 [[ 1.00198317  0.04285188 -0.04491185]]
Intercept: 
 [-0.10815401]
5613
10340
Coefficients: 
 [[ 1.00198317  0.04285188 -0.04491185]]
Intercept: 
 [-0.10815401]
5614
10340
Coefficients: 
 [[ 1.00202407  0.04277528 -0.04486906]]
Intercept: 
 [-0.11474663]
5615
10340
Coefficients: 
 [[ 1.00205386  0.04287584 -0.04499335]]
Intercept: 
 [-0.12038759]
5616
10340
Coefficients: 
 [[ 1.00205386  0.04287584 -0.04499335]]
Intercept: 
 [-0.12038759]
5617
10340
Coefficients: 
 [[ 1.00204998  0.04297257 -0.0450

Coefficients: 
 [[ 1.00217607  0.04246009 -0.04464018]]
Intercept: 
 [-0.17629776]
5707
10340
Coefficients: 
 [[ 1.00217891  0.04249327 -0.04467712]]
Intercept: 
 [-0.17543349]
5708
10340
Coefficients: 
 [[ 1.00217891  0.04249327 -0.04467712]]
Intercept: 
 [-0.17543349]
5709
10340
Coefficients: 
 [[ 1.0013116   0.04263093 -0.04393157]]
Intercept: 
 [-0.18998743]
5710
10340
Coefficients: 
 [[ 1.00131588  0.04264538 -0.04395456]]
Intercept: 
 [-0.18605381]
5711
10340
Coefficients: 
 [[ 1.00131588  0.04264538 -0.04395456]]
Intercept: 
 [-0.18605381]
5712
10340
Coefficients: 
 [[ 1.00128856  0.04262764 -0.04390704]]
Intercept: 
 [-0.18830477]
5713
10340
Coefficients: 
 [[ 1.00128856  0.04262764 -0.04390704]]
Intercept: 
 [-0.18830477]
5714
10340
Coefficients: 
 [[ 1.00128937  0.04266427 -0.04394039]]
Intercept: 
 [-0.19206208]
5715
10340
Coefficients: 
 [[ 1.00129513  0.0427253  -0.04401114]]
Intercept: 
 [-0.18843529]
5716
10340
Coefficients: 
 [[ 1.00129513  0.0427253  -0.04401114]]
Inte

Coefficients: 
 [[ 1.00006111  0.04516248 -0.04518449]]
Intercept: 
 [-0.21607889]
5813
10340
Coefficients: 
 [[ 1.00006111  0.04516248 -0.04518449]]
Intercept: 
 [-0.21607889]
5814
10340
Coefficients: 
 [[ 1.00001374  0.04334315 -0.0432757 ]]
Intercept: 
 [-0.25616421]
5815
10340
Coefficients: 
 [[ 0.99985182  0.04324987 -0.04300444]]
Intercept: 
 [-0.27149267]
5816
10340
Coefficients: 
 [[ 0.99985182  0.04324987 -0.04300444]]
Intercept: 
 [-0.27149267]
5817
10340
Coefficients: 
 [[ 0.99993533  0.04327482 -0.04311068]]
Intercept: 
 [-0.27366641]
5818
10340
Coefficients: 
 [[ 0.99993533  0.04327482 -0.04311068]]
Intercept: 
 [-0.27366641]
5819
10340
Coefficients: 
 [[ 0.99991756  0.04324822 -0.04306965]]
Intercept: 
 [-0.27039242]
5820
10340
Coefficients: 
 [[ 0.99991819  0.04330336 -0.04312715]]
Intercept: 
 [-0.26870867]
5821
10340
Coefficients: 
 [[ 0.99991819  0.04330336 -0.04312715]]
Intercept: 
 [-0.26870867]
5822
10340
Coefficients: 
 [[ 0.99989108  0.0433313  -0.04311811]]
Inte

Coefficients: 
 [[ 1.00009574  0.04240147 -0.04246532]]
Intercept: 
 [-0.21345546]
5913
10340
Coefficients: 
 [[ 1.00009574  0.04240147 -0.04246532]]
Intercept: 
 [-0.21345546]
5914
10340
Coefficients: 
 [[ 1.00012396  0.04249304 -0.04259296]]
Intercept: 
 [-0.20655631]
5915
10340
Coefficients: 
 [[ 0.99962819  0.04236221 -0.04195703]]
Intercept: 
 [-0.21446941]
5916
10340
Coefficients: 
 [[ 0.99962819  0.04236221 -0.04195703]]
Intercept: 
 [-0.21446941]
5917
10340
Coefficients: 
 [[ 0.99962516  0.04247577 -0.0420568 ]]
Intercept: 
 [-0.22375383]
5918
10340
Coefficients: 
 [[ 0.99962516  0.04247577 -0.0420568 ]]
Intercept: 
 [-0.22375383]
5919
10340
Coefficients: 
 [[ 0.99962317  0.04249157 -0.04207873]]
Intercept: 
 [-0.21675102]
5920
10340
Coefficients: 
 [[ 0.9996258   0.04252286 -0.04211068]]
Intercept: 
 [-0.21845615]
5921
10340
Coefficients: 
 [[ 0.9996258   0.04252286 -0.04211068]]
Intercept: 
 [-0.21845615]
5922
10340
Coefficients: 
 [[ 0.99963259  0.04258373 -0.04219122]]
Inte

Coefficients: 
 [[ 0.99944321  0.04255098 -0.04196319]]
Intercept: 
 [-0.21291126]
6008
10340
Coefficients: 
 [[ 0.99944321  0.04255098 -0.04196319]]
Intercept: 
 [-0.21291126]
6009
10340
Coefficients: 
 [[ 0.999444    0.04255572 -0.04196843]]
Intercept: 
 [-0.21315916]
6010
10340
Coefficients: 
 [[ 0.99942812  0.04245622 -0.04186625]]
Intercept: 
 [-0.20185397]
6011
10340
Coefficients: 
 [[ 0.99942812  0.04245622 -0.04186625]]
Intercept: 
 [-0.20185397]
6012
10340
Coefficients: 
 [[ 0.99942727  0.04249453 -0.04190889]]
Intercept: 
 [-0.19743104]
6013
10340
Coefficients: 
 [[ 0.99942727  0.04249453 -0.04190889]]
Intercept: 
 [-0.19743104]
6014
10340
Coefficients: 
 [[ 0.99944637  0.04245157 -0.04187794]]
Intercept: 
 [-0.20350435]
6015
10340
Coefficients: 
 [[ 0.99945088  0.04245    -0.04187515]]
Intercept: 
 [-0.20843007]
6016
10340
Coefficients: 
 [[ 0.99945088  0.04245    -0.04187515]]
Intercept: 
 [-0.20843007]
6017
10340
Coefficients: 
 [[ 0.99945011  0.04245322 -0.04187668]]
Inte

Coefficients: 
 [[ 0.99931322  0.04205463 -0.04144928]]
Intercept: 
 [-0.11865955]
6124
10340
Coefficients: 
 [[ 0.99932276  0.04207768 -0.04147986]]
Intercept: 
 [-0.12033908]
6125
10340
Coefficients: 
 [[ 0.99933549  0.04219472 -0.04161969]]
Intercept: 
 [-0.11200822]
6126
10340
Coefficients: 
 [[ 0.99933549  0.04219472 -0.04161969]]
Intercept: 
 [-0.11200822]
6127
10340
Coefficients: 
 [[ 0.99910749  0.04230129 -0.04148567]]
Intercept: 
 [-0.12232081]
6128
10340
Coefficients: 
 [[ 0.99910749  0.04230129 -0.04148567]]
Intercept: 
 [-0.12232081]
6129
10340
Coefficients: 
 [[ 0.99911888  0.04229849 -0.04150273]]
Intercept: 
 [-0.11536037]
6130
10340
Coefficients: 
 [[ 0.99911582  0.04230073 -0.04150142]]
Intercept: 
 [-0.11576131]
6131
10340
Coefficients: 
 [[ 0.99911582  0.04230073 -0.04150142]]
Intercept: 
 [-0.11576131]
6132
10340
Coefficients: 
 [[ 0.99912154  0.04227756 -0.04148847]]
Intercept: 
 [-0.11207615]
6133
10340
Coefficients: 
 [[ 0.99912154  0.04227756 -0.04148847]]
Inte

Coefficients: 
 [[ 0.9985406   0.0423395  -0.04093972]]
Intercept: 
 [-0.1364534]
6220
10340
Coefficients: 
 [[ 0.99855072  0.04235886 -0.04096514]]
Intercept: 
 [-0.13980204]
6221
10340
Coefficients: 
 [[ 0.99855072  0.04235886 -0.04096514]]
Intercept: 
 [-0.13980204]
6222
10340
Coefficients: 
 [[ 0.99856038  0.04235299 -0.0409727 ]]
Intercept: 
 [-0.13669728]
6223
10340
Coefficients: 
 [[ 0.99856038  0.04235299 -0.0409727 ]]
Intercept: 
 [-0.13669728]
6224
10340
Coefficients: 
 [[ 0.99856106  0.042353   -0.04097401]]
Intercept: 
 [-0.13620354]
6225
10340
Coefficients: 
 [[ 0.99856143  0.04235686 -0.04097803]]
Intercept: 
 [-0.13637197]
6226
10340
Coefficients: 
 [[ 0.99856143  0.04235686 -0.04097803]]
Intercept: 
 [-0.13637197]
6227
10340
Coefficients: 
 [[ 0.99858539  0.04249972 -0.04116303]]
Intercept: 
 [-0.12153041]
6228
10340
Coefficients: 
 [[ 0.99858539  0.04249972 -0.04116303]]
Intercept: 
 [-0.12153041]
6229
10340
Coefficients: 
 [[ 0.99857896  0.04237389 -0.04102122]]
Inter

 [[ 0.99877125  0.04278654 -0.04160866]]
Intercept: 
 [-0.14403617]
6322
10340
Coefficients: 
 [[ 0.99873987  0.04271776 -0.04149765]]
Intercept: 
 [-0.15293391]
6323
10340
Coefficients: 
 [[ 0.99873987  0.04271776 -0.04149765]]
Intercept: 
 [-0.15293391]
6324
10340
Coefficients: 
 [[ 0.99872789  0.04275468 -0.04151658]]
Intercept: 
 [-0.1578793]
6325
10340
Coefficients: 
 [[ 0.99873741  0.04281269 -0.04158799]]
Intercept: 
 [-0.15469119]
6326
10340
Coefficients: 
 [[ 0.99873741  0.04281269 -0.04158799]]
Intercept: 
 [-0.15469119]
6327
10340
Coefficients: 
 [[ 0.99866887  0.04299673 -0.04169035]]
Intercept: 
 [-0.16547556]
6328
10340
Coefficients: 
 [[ 0.99866887  0.04299673 -0.04169035]]
Intercept: 
 [-0.16547556]
6329
10340
Coefficients: 
 [[ 0.9986636   0.04290294 -0.04160327]]
Intercept: 
 [-0.15565448]
6330
10340
Coefficients: 
 [[ 0.9986624   0.04294735 -0.04165231]]
Intercept: 
 [-0.15089199]
6331
10340
Coefficients: 
 [[ 0.9986624   0.04294735 -0.04165231]]
Intercept: 
 [-0.150

ValueError: Found input variables with inconsistent numbers of samples: [3843, 3842]